project_name: goreleaser-testing

before:
  hooks:
    - go mod tidy

builds:
  - binary: goreleaser-testing
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

universal_binaries:
  - replace: true

release:
  github:
    owner: robinovitch61
    name: goreleaser-testing

brews:
  - name: goreleaser-testing
    homepage: https://github.com/robinovitch61/goreleaser-testing
    description: "Goreleaser testing description"
    folder: Formula
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@theleo.zone
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    repository:
      owner: robinovitch61
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

nix:
  - name: goreleaser-testing
    commit_author:
      name: "Leo Robinovitch"
      email: "leorobinovitch@gmail.com"
    homepage: https://github.com/robinovitch61/goreleaser-testing
    description: "Goreleaser testing description"
    license: "mit"  # must be lowercase
    skip_upload: auto
    repository:
      owner: robinovitch61
      name: nur-packages
      branch: main
      token: "{{ .Env.NUR_PACKAGES_GITHUB_TOKEN }}"

winget:
  - publisher: robinovitch61
    license: MIT
    copyright: "Leo Robinovitch"
    homepage: https://github.com/robinovitch61/goreleaser-testing
    short_description: "Goreleaser testing description"
    package_identifier: "robinovitch61.goreleaser-testing"
    repository:
      owner: "robinovitch61"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      name: winget-pkgs
      branch: "{{.ProjectName}}-{{.Version}}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master

chocolateys:
  - owners: "Leo Robinovitch"
    authors: "Leo Robinovitch"
    project_url: https://github.com/robinovitch61/goreleaser-testing
    url_template: "https://github.com/robinovitch61/goreleaser-testing/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    license_url: https://github.com/robinovitch61/goreleaser-testing/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/robinovitch61/goreleaser-testing
    docs_url: https://github.com/robinovitch61/goreleaser-testing/blob/main/README.md
    bug_tracker_url: https://github.com/robinovitch61/goreleaser-testing/issues
    tags: "foo bar"
    summary: "Goreleaser testing summary"
    description: |
      # Goreleaser testing description
      
      This is a test package for validating goreleaser releases.
    release_notes: "https://github.com/robinovitch61/goreleaser-testing/releases/tag/v{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false

gomod:
  proxy: true
