project_name: goreleaser-testing

before:
  hooks:
    - go mod tidy

builds:
  - binary: goreleaser-testing
    env:
      - CGO_ENABLED=0
    goos:
      - windows

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.windows.txt'

chocolateys:
  - owners: "Leo Robinovitch"
    authors: "Leo Robinovitch"
    project_url: https://github.com/robinovitch61/goreleaser-testing
    url_template: "https://github.com/robinovitch61/goreleaser-testing/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    copyright: None
    license_url: https://github.com/robinovitch61/goreleaser-testing/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/robinovitch61/goreleaser-testing
    docs_url: https://github.com/robinovitch61/goreleaser-testing/blob/main/README.md
    bug_tracker_url: https://github.com/robinovitch61/goreleaser-testing/issues
    tags: "foo bar"
    summary: "Goreleaser testing summary"
    description: "Goreleaser testing description"
    release_notes: "https://github.com/robinovitch61/goreleaser-testing/releases/tag/v{{ .Version }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false

gomod:
  proxy: true
